[package]
name = "joins"
version = "0.1.0"
authors = ["main() <main@ehvag.de>"]
edition = "2018"

[dependencies]
futures = "0.1.27"
multimap = "0.5"
named_type = "0.2.1"
named_type_derive = "0.2.1"
fraction = "0.6.2"
itertools = "0.8"
debug-everything = "1.0"
